### ISSUE TITLE
Should add "na.rm=TRUE" to calls to "min(.)"

### ISSUE THREAD

**Issue by ghost** [johnmyleswhite/bayesian_nonparametrics#3]
The calls to the "min(.)" function in lines 28 and 36 of dp-means.R ought to have an "na.rm=TRUE" added. Specifically, they should be, in turn,

```
if (min(distances, na.rm=TRUE) > lambda)
```

and

```
assignments[i] <- which(distances == min(distances, na.rm=TRUE))
```

This is because NAs sometimes leak through in `distances`, given its definition in line 21.

**Comment by johnmyleswhite** [comment]
Thanks for the suggestion. This is a non-maintained repo.
